import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const METHOD_JSON = join(HERE, "..", "capabilities", "method", "method.json");

const raw = JSON.parse(readFileSync(METHOD_JSON, "utf8"));
const storeData = raw.datasets.store;

/**
 * The literal, bracket-free name of the operación-track folder on disk before a company is known,
 * and the only path SEGMENT this module ever renames. `<empresa>` in the playbook's own notation
 * (A2 §2, `packages/method/src/data/store.json`) is prose, not a filename: `<` and `>` are illegal
 * on NTFS and are silently remapped to private-use codepoints by an MSYS shell, which breaks every
 * later `readdirSync`/path comparison — verified empirically while building this layout. Everything
 * after this segment is never rewritten.
 */
export const MAPEO_TEMPLATE_ROOT = "mapeo-empresa";

/**
 * Extra skills that also write a document, beyond the single `ownerSkill` the playbook's store
 * table carries per path (`packages/method/src/data/store.json` in the Web repository, A2 §2). The
 * vendored table is one-owner-per-row by design (Ruling 3); a few plugin documents are legitimately
 * touched by more than one skill, and that fan-out is plugin mechanics, not method, so it stays here
 * rather than in the vendored data it would otherwise have to restate.
 */
const EXTRA_OWNERS = {
  "mapeo-<empresa>/03-procesos/PXX-<nombre>.md": ["process-access"],
  "mapeo-<empresa>/04-evidencia/ENTREVISTAS.md": [
    "company-profile",
    "company-evidence",
    "process-map",
    "process-access",
  ],
  "mapeo-<empresa>/02-inventario.md": ["company-evidence"],
  "mapeo-<empresa>/05-backlog.md": ["opportunities"],
  "mapeo-<empresa>/09-rutinas.md": ["report", "process-access"],
  "comunicacion/PROOF.md": ["social-voice"],
  "comunicacion/SOCIAL.md": ["social-plan"],
};

/**
 * Converts a store path's bracketed placeholders into the literal, bracket-free words
 * `scaffold/company/` actually uses on disk (`mapeo-empresa/`, `PXX-nombre.md`, `AXX-nombre.md`).
 * The store table keeps the brackets because it is prose, read as a table cell, not a path this
 * process opens; every real file and directory in this repository uses this converted form.
 */
export const toTemplatePath = (path) =>
  path.replace("<empresa>", "empresa").replace("<AXX>", "AXX").replace("<nombre>", "nombre");

/**
 * A document whose path names a family of files (`PXX-nombre.md`, `AXX-nombre.md`) or a directory
 * (`07-datos/`) rather than one file — checked by pattern or by directory presence, never by exact
 * existence.
 */
export const isFamily = (templatePath) => /-nombre\.md$|\/$/.test(templatePath);

/**
 * The company store's document layout, read from the vendored copy of the playbook's `store.json`
 * (`capabilities/method/method.json`, generated by the Web repository's `pnpm --filter method
 * export` and never edited here). Each entry carries the SSOT `path` (bracketed, e.g.
 * `mapeo-<empresa>/00-PERFIL.md`), its bracket-free `templatePath` (e.g. `mapeo-empresa/00-PERFIL.md`,
 * matching `scaffold/company/` on disk), `owners` (the vendored `ownerSkill` plus `EXTRA_OWNERS`),
 * and `family` (true for a per-item or directory document).
 */
export const STORE_DOCUMENTS = [...storeData.entries, ...storeData.communicationDocuments].map(
  (entry) => {
    const templatePath = toTemplatePath(entry.path);
    return {
      ...entry,
      templatePath,
      owners: [entry.ownerSkill, ...(EXTRA_OWNERS[entry.path] ?? [])],
      family: isFamily(templatePath),
    };
  }
);

/**
 * Characters NTFS (and this repository's own MSYS shell) cannot hold in a path segment, collapsed
 * to a hyphen. A company's legal name routinely carries a slash or a quote — "Juan Pérez y
 * Asociados, S.C." is the tame case — and the FOLDER segment is the one place that name becomes a
 * path component rather than prose; the substitution inside a document's own text is untouched.
 */
const FOLDER_UNSAFE = /[\\/:*?"<>|]+/g;

/** The company-name folder segment, sanitised for the filesystem. */
export const folderSlug = (companyName) => companyName.replace(FOLDER_UNSAFE, "-").trim();

/**
 * Replaces the leading `mapeo-empresa` folder SEGMENT of a template path with `mapeo-<nombre>` once
 * a company name is known. Every other segment — a process or automation's own chosen name — is
 * never touched. Left intact when no name is known, matching `tools/scaffold.mjs`'s own rule: a
 * placeholder is never filled from a guess.
 */
export const resolveForCompany = (templatePath, companyName) =>
  companyName && templatePath.startsWith(`${MAPEO_TEMPLATE_ROOT}/`)
    ? `mapeo-${folderSlug(companyName)}/${templatePath.slice(MAPEO_TEMPLATE_ROOT.length + 1)}`
    : templatePath;

/**
 * Turns a family template's `PXX`/`AXX`/`nombre` segment into a matching filename regex, anchored so
 * `INDICE.md` and `REGISTRO.md` — the index files living beside the family in the same directory —
 * never match by accident.
 */
export const familyPattern = (templatePath) => {
  const base = templatePath.split("/").pop();
  const escaped = base
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace("PXX", "P\\d+")
    .replace("AXX", "A\\d+")
    .replace("nombre", ".+");
  return new RegExp(`^${escaped}$`);
};

/** The directory a family template or a directory-only template resolves to, for a bound company. */
export const familyDir = (templatePath, companyName) => {
  const resolved = resolveForCompany(templatePath, companyName);
  return templatePath.endsWith("/") ? resolved : dirname(resolved);
};
